version: '3.8'
services:
    client:
        container_name: react-vite
        build:
            context: ./docker
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        environment:
            - TZ=Asia/Ho_Chi_Minh
